server:
  port : 9090
spring:
  application:
    name: ExchangeRateService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

national-bank:
  rates-url: https://nationalbank.kz/rss/rates_all.xml

loader:
  crone: 0 * * * * *


